kind: Service
apiVersion: v1
metadata:
  name: api-server
  labels:
    name: api-server
spec:
  ports:
  - port: 9001
    protocol: TCP
  selector:           
    app: api-server

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  namespace: test
  name: api-server
spec:                
  selector:         
    matchLabels:
      app: api-server
  replicas: 1        
  template:
    metadata:
      labels:        
        app: api-server
    spec:
      containers:
        - name: api-server
          image: nginx:1.14.2
          ports:
            - containerPort: 8080    
